CREATE DATABASE GARAOTO
GO
USE GARAOTO
CREATE TABLE HIEUXE
(
    MAHIEUXE INT IDENTITY PRIMARY KEY,
    TENHIEUXE NVARCHAR(40)
)
CREATE TABLE CHUXE
(
    MACHUXE INT IDENTITY(1,1) PRIMARY KEY,
    TENCHUXE NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(100),
    DIENTHOAI NVARCHAR(20) NOT NULL,
    EMAIL NVARCHAR(50)   
)
ALTER TABLE CHUXE
ADD CONSTRAINT UQ_DIENTHOAI UNIQUE(DIENTHOAI);
CREATE INDEX idx_DT 
ON CHUXE(DIENTHOAI)

CREATE TABLE THAMSO
(
	MATHAMSO INT IDENTITY,
	TENTHAMSO NVARCHAR(40),
	GIATRI INT
)
ALTER TABLE THAMSO 
ADD CONSTRAINT PK_THAMSO PRIMARY KEY (MATHAMSO)
CREATE TABLE BAOCAO
(
	MABAOCAO INT IDENTITY PRIMARY KEY,
	THANGNAM SMALLDATETIME,
	TONGDOANHTHU MONEY DEFAULT 0
)
CREATE TABLE CT_BCDS
(
	MACTBCDS INT IDENTITY PRIMARY KEY,
	THANGNAM SMALLDATETIME,
	MAHIEUXE INT,
	SOLUOTSUA INT,
	THANHTIEN MONEY DEFAULT 0,
	TYLE FLOAT,
	CONSTRAINT FK_CTBCDS_HX FOREIGN KEY (MAHIEUXE) REFERENCES HIEUXE(MAHIEUXE)
)

CREATE TABLE PHIEUNHAP
(	
	SOPHIEUNHAP INT IDENTITY PRIMARY KEY,
	NGAYLAP SMALLDATETIME,
	TONGTIEN MONEY
)
ALTER TABLE PHIEUNHAP
ADD TINHTRANG	SMALLINT DEFAULT 0 -- 0 PRESENTED FOR IS OPENING
								-- 1 PRESENTED FOR WAS CLOSED

GO
--We need this trigger but in this case to reduce the pressure on the server we will handle this in client
--CREATE OR ALTER TRIGGER trg_c_PHIEUNHAP ON PHIEUNHAP
--FOR INSERT
--AS
--BEGIN
--	IF (SELECT COUNT(*)
--		FROM PHIEUNHAP
--		WHERE TINHTRANG = 0) > 1
--	BEGIN
--		ROLLBACK TRAN
--	END 
--END
DROP TRIGGER trg_c_PHIEUNHAP
CREATE TABLE PHUTUNG
(	
	MAPHUTUNG INT IDENTITY PRIMARY KEY,
	TENPHUTUNG NVARCHAR(50),
	DONGIA MONEY,
	SOLUONGTON INT,
)
SELECT * FROM BAOCAOTON
DELETE FROM BAOCAOTON
ALTER TABLE PHUTUNG
ALTER COLUMN TENPHUTUNG NVARCHAR(500)
CREATE TABLE BAOCAOTON
(
	MABAOCAOTON INT IDENTITY PRIMARY KEY,
	THANGNAM SMALLDATETIME,
	MAPHUTUNG INT,
	TONDAU INT DEFAULT 0,
	SLNHAP INT DEFAULT 0,
	SLBAN INT DEFAULT 0,
	TONCUOI INT DEFAULT 0,
	CONSTRAINT FK_BCT_PT FOREIGN KEY (MAPHUTUNG)  REFERENCES PHUTUNG(MAPHUTUNG)
)
CREATE OR ALTER TRIGGER trg_i_PHUTUNG ON PHUTUNG
FOR INSERT
AS
BEGIN
	DECLARE @TN SMALLDATETIME
	SET @TN = GETDATE()
	EXEC INITBAOCAOTON @THANGNAM = @TN
	INSERT INTO BAOCAOTON(THANGNAM, MAPHUTUNG, TONDAU)
	SELECT GETDATE(), MAPHUTUNG, SOLUONGTON
	FROM inserted
END

CREATE TABLE CT_PHIEUNHAP
(
	SOPHIEUNHAP INT,
	MAPHUTUNG INT,
	SOLUONGNHAP INT NOT NULL,
	DONGIA MONEY NOT NULL,
	THANHTIEN MONEY DEFAULT 0,
	CONSTRAINT PK_CT_PN PRIMARY KEY (SOPHIEUNHAP, MAPHUTUNG),
	CONSTRAINT FK_CT_PN FOREIGN KEY (SOPHIEUNHAP) REFERENCES PHIEUNHAP(SOPHIEUNHAP),
	CONSTRAINT FK_CT_PT FOREIGN KEY (MAPHUTUNG) REFERENCES PHUTUNG(MAPHUTUNG)
)
CREATE OR ALTER TRIGGER trg_iu_CTPHIEUNHAP ON CT_PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	UPDATE CT_PHIEUNHAP
	SET THANHTIEN = SOLUONGNHAP*DONGIA
	WHERE SOPHIEUNHAP in (SELECT SOPHIEUNHAP
							FROM inserted)
END
CREATE OR ALTER PROC GETCURRENTPHUTUNG
@SOPHIEUNHAP INT
AS 
BEGIN
	INSERT INTO CT_PHIEUNHAP(SOPHIEUNHAP, MAPHUTUNG, SOLUONGNHAP, DONGIA)
	SELECT @SOPHIEUNHAP, MAPHUTUNG, 1, DONGIA
	FROM PHUTUNG pt
	WHERE MAPHUTUNG not in (SELECT MAPHUTUNG 
							FROM CT_PHIEUNHAP 
							WHERE SOPHIEUNHAP = @SOPHIEUNHAP)
END
CREATE OR ALTER PROC GETCURRENTPHUTUNGTOSELECT
@SOPHIEUNHAP INT
AS
BEGIN
	SELECT *
	FROM PHUTUNG 
	WHERE MAPHUTUNG not in (SELECT MAPHUTUNG
							FROM CT_PHIEUNHAP
							WHERE SOPHIEUNHAP = @SOPHIEUNHAP)
END
CREATE OR ALTER PROC SETNUMBERFORALLELEMENT
@SOPHIEUNHAP  INT,
@SOLUONG INT
AS
BEGIN 
	UPDATE CT_PHIEUNHAP
	SET SOLUONGNHAP = @SOLUONG
	WHERE SOPHIEUNHAP = @SOPHIEUNHAP
END
CREATE OR ALTER PROC SETPRICE4ALLELEMENT
@SOPHIEUNHAP INT,
@GIA MONEY
AS
BEGIN
	UPDATE CT_PHIEUNHAP
	SET DONGIA =  @GIA
	WHERE SOPHIEUNHAP = @SOPHIEUNHAP
END
SELECT * FROM PHIEUNHAP
INSERT INTO PHIEUNHAP(NGAYLAP, TONGTIEN, TINHTRANG) VALUES ('20221221',0,0)
CREATE OR ALTER PROC DONGPHIEUNHAP
@SOPHIEUNHAP INT
AS
BEGIN

	UPDATE PHIEUNHAP SET TINHTRANG = 1 WHERE SOPHIEUNHAP = @SOPHIEUNHAP
	UPDATE PHUTUNG 
	SET SOLUONGTON = (SELECT SOLUONGTON + SUM(SOLUONGNHAP)
					FROM CT_PHIEUNHAP
					WHERE SOPHIEUNHAP = @SOPHIEUNHAP and MAPHUTUNG = PHUTUNG.MAPHUTUNG)
	WHERE MAPHUTUNG IN (SELECT MAPHUTUNG 
						FROM CT_PHIEUNHAP
						WHERE SOPHIEUNHAP =  @SOPHIEUNHAP)
	UPDATE PHUTUNG 
	SET DONGIA = (SELECT DONGIA
					FROM CT_PHIEUNHAP
					WHERE SOPHIEUNHAP = @SOPHIEUNHAP and MAPHUTUNG = PHUTUNG.MAPHUTUNG)
	WHERE MAPHUTUNG IN (SELECT MAPHUTUNG 
						FROM CT_PHIEUNHAP
						WHERE SOPHIEUNHAP =  @SOPHIEUNHAP)
	UPDATE PHIEUNHAP
	SET TONGTIEN = (SELECT SUM(THANHTIEN)
					FROM CT_PHIEUNHAP
					WHERE SOPHIEUNHAP = PHIEUNHAP.SOPHIEUNHAP)
	WHERE SOPHIEUNHAP = @SOPHIEUNHAP
END
EXEC DONGPHIEUNHAP @SOPHIEUNHAP = 1
CREATE TABLE THANGNAM
(
	MATHANGNAM INT IDENTITY PRIMARY KEY,
	THANG INT,
	NAM INT
)
CREATE TABLE XE 
(
	MAXE INT IDENTITY(1000,1) PRIMARY KEY,
	BIENSO NVARCHAR(20) NOT NULL,
	MAHIEUXE INT,
	MACHUXE INT,
	NGAYTIEPNHAN SMALLDATETIME,
	TONGNO MONEY,
	CONSTRAINT FK_XE_CX FOREIGN KEY (MACHUXE) REFERENCES CHUXE(MACHUXE),
	CONSTRAINT FK_XE_HX FOREIGN KEY (MAHIEUXE) REFERENCES HIEUXE(MAHIEUXE)
)
ALTER TABLE XE
ADD CONSTRAINT UQ_BIENXO UNIQUE(BIENSO)

ALTER TABLE XE
ADD TINHTRANG SMALLINT DEFAULT 1	-- 0 PRESENTED FOR IS OPENING
										-- 1 PRESENTED FOR WAS CLOSED
CREATE TABLE PHIEUTHUTIEN
(
	MAPHIEUTHU INT IDENTITY PRIMARY KEY,
	NGAYTHU SMALLDATETIME,
	MAXE INT,
	SOTIENTHU MONEY,
	CONSTRAINT FK_PTT_XE FOREIGN KEY (MAXE) REFERENCES XE(MAXE)
)
CREATE TABLE PHIEUSUACHUA
(
	MAPHIEU INT IDENTITY PRIMARY KEY,
	MAXE INT,
	NGAYLAP SMALLDATETIME,
	TONGTIEN MONEY DEFAULT 0,

	CONSTRAINT FK_PSC_XE FOREIGN KEY (MAXE) REFERENCES XE(MAXE)
)

ALTER TABLE PHIEUSUACHUA
ADD TINHTRANG SMALLINT DEFAULT 0 -- 0 PRESENTED FOR IS OPENING
								-- 1 PRESENTED FOR WAS CLOSED
--We need this trigger but in this case to reduce the pressure on the server we will handle this in client
--CREATE OR ALTER TRIGGER trg_c_PHIEUSUACHUA ON PHIEUSUACHUA
--FOR INSERT
--AS
--BEGIN
--similar above
--END

SELECT * FROM PHIEUSUACHUA
SELECT * FROM XE
SELECT * FROM CHITIET_PSC



CREATE OR ALTER TRIGGER trg_i_PHIEUSUACHUA ON PHIEUSUACHUA
FOR INSERT
AS
BEGIN
	UPDATE XE SET TINHTRANG = 0
	WHERE MAXE in (SELECT MAXE 
					FROM inserted)
END

CREATE OR ALTER TRIGGER trg_d_PHIEUSUACHUA ON PHIEUSUACHUA
FOR DELETE
AS
BEGIN
	UPDATE XE SET TINHTRANG = 1
	WHERE MAXE in (SELECT MAXE 
					FROM deleted
					WHERE TINHTRANG = 0)
END

CREATE TABLE TIENCONG
(
	MANDTC INT IDENTITY PRIMARY KEY,
	NOIDUNG NVARCHAR(100),
	TIENCONG MONEY
)
ALTER TABLE TIENCONG
ALTER COLUMN NOIDUNG NVARCHAR(500)
CREATE TABLE CHITIET_PSC
(
	MACTPSC INT IDENTITY PRIMARY KEY,
	MAPHIEU INT,
	MANDTC INT,
	TIENCONG MONEY,
	MAPHUTUNG INT,
	SOLUONG INT,
	DONGIA MONEY,
	THANHTIEN MONEY,
	CONSTRAINT FK_CT_TC FOREIGN KEY (MANDTC) REFERENCES TIENCONG(MANDTC),
	CONSTRAINT FK_CT_PH FOREIGN KEY (MAPHUTUNG) REFERENCES PHUTUNG(MAPHUTUNG),
	CONSTRAINT FK_CT_PSC FOREIGN KEY (MAPHIEU) REFERENCES PHIEUSUACHUA(MAPHIEU) 
)

CREATE OR ALTER TRIGGER trg_iu_CHITIET_PSC ON CHITIET_PSC
FOR INSERT
AS
BEGIN
	UPDATE PHUTUNG
	SET SOLUONGTON =  (SELECT SOLUONGTON - SOLUONG
						FROM inserted
						WHERE MAPHUTUNG = PHUTUNG.MAPHUTUNG)
	WHERE MAPHUTUNG in (SELECT MAPHUTUNG FROM inserted)
END
SELECT * FROM PHUTUNG
CREATE OR ALTER TRIGGER trg_du_CHITIET_PSC ON CHITIET_PSC
FOR DELETE
AS
BEGIN
	UPDATE PHUTUNG
	SET SOLUONGTON =  (SELECT SOLUONGTON + SOLUONG
						FROM deleted
						WHERE MAPHUTUNG = PHUTUNG.MAPHUTUNG)
	WHERE MAPHUTUNG in (SELECT MAPHUTUNG FROM deleted)
END
SELECT * FROM BAOCAOTON
CREATE TABLE ACCOUNT
(
	USERID INT IDENTITY(100,1) PRIMARY KEY,
	USERNAME NVARCHAR(40)  NOT NULL UNIQUE,
	PASSWORD NVARCHAR(1000) NOT NULL,
	DISPLAYNAME NVARCHAR(50),
	DESCRIPTION NVARCHAR(1000),
	TYPE INT DEFAULT 2, -- 2 REPRESENT FOR STAFF, 1 REPRESENT FOR  MANAGER, 0 REPRESENT FOR SYSTEM ADMIN
)
INSERT INTO THAMSO(TENTHAMSO, GIATRI) VALUES ('SOXESUACHUATOIDA', 30)
INSERT INTO THAMSO(TENTHAMSO, GIATRI) VALUES ('THUVUOTQUANO', 1)
INSERT INTO THAMSO(TENTHAMSO, GIATRI) VALUES ('TYLEGIALINHKIENBANRA', 105)
GO
CREATE PROC LOGINACCOUNT
@USERNAME NVARCHAR(40), @PASSWORD NVARCHAR(1000)
AS 
BEGIN
	SELECT * FROM ACCOUNT ac WHERE ac.USERNAME = @USERNAME and ac.PASSWORD = @PASSWORD
END
GO
SELECT * FROM XE
SELECT * FROM PHIEUSUACHUA
SELECT * FROM CHITIET_PSC
SELECT * FROM PHUTUNG

SELECT * FROM BAOCAOTON

EXEC DONGPHIEUSUACHUA @MAPHIEU = 164, @TONGTIEN2 = 3960000
CREATE OR ALTER PROC DONGPHIEUSUACHUA
@MAPHIEU INT,
@TONGTIEN2 MONEY
AS
BEGIN
	UPDATE PHIEUSUACHUA SET TINHTRANG = 1 WHERE MAPHIEU = @MAPHIEU

	DECLARE @MAXE INT
	SELECT TOP 1  @MAXE = MAXE 
	FROM PHIEUSUACHUA
	WHERE MAPHIEU = @MAPHIEU
	UPDATE XE SET TONGNO = TONGNO +  @TONGTIEN2 WHERE MAXE = @MAXE
	UPDATE XE SET TINHTRANG = 1 WHERE MAXE = @MAXE
	DECLARE @NGAYLAP SMALLDATETIME
	SELECT TOP 1 @NGAYLAP = NGAYLAP
	FROM PHIEUSUACHUA
	WHERE MAPHIEU = @MAPHIEU
END
CREATE OR ALTER PROC XOAPHIEUSUACHUA
@MAPHIEU INT
AS
BEGIN
	DELETE FROM CHITIET_PSC WHERE MAPHIEU = @MAPHIEU
	DELETE FROM PHIEUSUACHUA WHERE MAPHIEU = @MAPHIEU
END
SELECT * FROM PHIEUSUACHUA
SELECT * FROM PHUTUNG


CREATE OR ALTER PROC INITBAOCAOTON
@THANGNAM SMALLDATETIME
AS
BEGIN
	IF NOT EXISTS (SELECT *
	FROM BAOCAOTON
	WHERE YEAR(THANGNAM) = YEAR(@THANGNAM) and MONTH(THANGNAM) = MONTH(@THANGNAM))
	BEGIN
		INSERT INTO BAOCAOTON(THANGNAM,MAPHUTUNG, TONDAU, SLNHAP, SLBAN,  TONCUOI)
		SELECT @THANGNAM, MAPHUTUNG,SOLUONGTON, 0,0,SOLUONGTON
		FROM PHUTUNG
	END
END
CREATE OR ALTER PROC GETBAOCAOTON
@THANG INT,
@NAM INT
AS
BEGIN
	UPDATE BAOCAOTON
	SET SLBAN = (SELECT SUM(SOLUONG)
				FROM CHITIET_PSC ct join PHIEUSUACHUA psc  on psc.MAPHIEU = ct.MAPHIEU
				WHERE MAPHUTUNG = BAOCAOTON.MAPHUTUNG AND YEAR(NGAYLAP) = @NAM AND MONTH(NGAYLAP) = @THANG 
				GROUP BY MAPHUTUNG) 
	WHERE YEAR(THANGNAM) = @NAM AND MONTH(THANGNAM) = @THANG
	AND MAPHUTUNG in (	SELECT ct.MAPHUTUNG
						FROM CHITIET_PSC ct join PHIEUSUACHUA psc  on psc.MAPHIEU = ct.MAPHIEU
						WHERE YEAR(NGAYLAP) = @NAM AND MONTH(NGAYLAP) = @THANG )

	UPDATE BAOCAOTON
	SET SLNHAP = (SELECT SUM(SOLUONGNHAP)
				FROM CT_PHIEUNHAP ct join PHIEUNHAP pn on ct.SOPHIEUNHAP = pn.SOPHIEUNHAP
				WHERE YEAR(NGAYLAP) = @NAM and MONTH(NGAYLAP) = @THANG AND MAPHUTUNG  = BAOCAOTON.MAPHUTUNG
				GROUP BY MAPHUTUNG)
	WHERE YEAR(THANGNAM) = @NAM and MONTH(THANGNAM) = @THANG 
	AND MAPHUTUNG IN (SELECT MAPHUTUNG
					FROM CT_PHIEUNHAP ct join PHIEUNHAP pn on ct.SOPHIEUNHAP = pn.SOPHIEUNHAP
					WHERE YEAR(NGAYLAP) = @NAM and MONTH(NGAYLAP) = @THANG)

	UPDATE BAOCAOTON SET SLBAN = 0 WHERE SLBAN IS NULL AND YEAR(THANGNAM) = @NAM and MONTH(THANGNAM) = @THANG 
	UPDATE BAOCAOTON SET SLNHAP = 0 WHERE SLNHAP IS NULL AND YEAR(THANGNAM) = @NAM and MONTH(THANGNAM) = @THANG 
	UPDATE BAOCAOTON SET TONCUOI = TONDAU + SLNHAP - SLBAN WHERE YEAR(THANGNAM) = @NAM and MONTH(THANGNAM) = @THANG 

	SELECT pt.TENPHUTUNG, TONDAU, SLNHAP, SLBAN, TONCUOI
	FROM BAOCAOTON bct join PHUTUNG pt on bct.MAPHUTUNG = pt.MAPHUTUNG
	WHERE YEAR(THANGNAM) = @NAM AND MONTH(THANGNAM) = @THANG
	ORDER BY SLBAN DESC
END
EXEC GETBAOCAOTON @THANG = 12, @NAM = 2022
SELECT * FROM BAOCAOTON

GO
CREATE OR ALTER PROC INITBAOCAODOANHSO
@THANGNAM SMALLDATETIME
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM BAOCAO WHERE YEAR(THANGNAM) = YEAR(@THANGNAM) and MONTH(THANGNAM) = MONTH(@THANGNAM))
	BEGIN
		DECLARE @TONGDOANHSO MONEY
		SELECT @TONGDOANHSO = SUM(psc.TONGTIEN)
		FROM PHIEUSUACHUA psc
		WHERE YEAR(psc.NGAYLAP) = YEAR(@THANGNAM) and MONTH(psc.NGAYLAP) = MONTH(@THANGNAM)
		
		INSERT INTO BAOCAO(THANGNAM,TONGDOANHTHU) VALUES (@THANGNAM,@TONGDOANHSO)

		INSERT INTO CT_BCDS(THANGNAM, MAHIEUXE, SOLUOTSUA, THANHTIEN, TYLE) 
		SELECT @THANGNAM, hx.MAHIEUXE, COUNT(psc.MAPHIEU), SUM(psc.TONGTIEN), SUM(psc.TONGTIEN)/@TONGDOANHSO
		FROM HIEUXE hx LEFT JOIN XE x  on x.MAHIEUXE = hx.MAHIEUXE
			join PHIEUSUACHUA psc on psc.MAXE = x.MAXE
		WHERE YEAR(psc.NGAYLAP) = YEAR(@THANGNAM) and MONTH(psc.NGAYLAP) = MONTH(@THANGNAM)
		GROUP BY hx.MAHIEUXE
	END ELSE
	BEGIN
		SELECT @TONGDOANHSO = SUM(psc.TONGTIEN)
		FROM PHIEUSUACHUA psc
		WHERE YEAR(psc.NGAYLAP) = YEAR(@THANGNAM) and MONTH(psc.NGAYLAP) = MONTH(@THANGNAM)
		UPDATE BAOCAO SET TONGDOANHTHU = @TONGDOANHSO WHERE YEAR(THANGNAM) = YEAR(@THANGNAM) and MONTH(THANGNAM) = MONTH(@THANGNAM)

		MERGE CT_BCDS as ct 
		USING 
		(
			SELECT hx.MAHIEUXE as MAHIEUXE, COUNT(psc.MAPHIEU) as SOLUOTSUA, SUM(psc.TONGTIEN) as TONGTIEN, SUM(psc.TONGTIEN)/@TONGDOANHSO as TYLE
			FROM HIEUXE hx LEFT JOIN XE x  on x.MAHIEUXE = hx.MAHIEUXE
			join PHIEUSUACHUA psc on psc.MAXE = x.MAXE
			WHERE YEAR(psc.NGAYLAP) = YEAR(@THANGNAM) and MONTH(psc.NGAYLAP) = MONTH(@THANGNAM)
			GROUP BY hx.MAHIEUXE
		) newCT
		ON ct.MAHIEUXE = newCT.MAHIEUXE
		WHEN MATCHED THEN
		UPDATE SET
		ct.SOLUOTSUA =  newCT.SOLUOTSUA,
		ct.THANHTIEN = newCT.TONGTIEN,
		ct.TYLE = newCT.TYLE;
	END
END
GO
CREATE OR ALTER PROC GETCHITIETBAOCAO
@THANG INT,
@NAM INT
AS
BEGIN
	SELECT hx.MAHIEUXE ,hx.TENHIEUXE, COUNT(psc.MAPHIEU) as SOLUOTSUA, SUM(psc.TONGTIEN) as THANHTIEN
	FROM HIEUXE hx JOIN XE x on hx.MAHIEUXE = x.MAHIEUXE
		JOIN PHIEUSUACHUA psc ON psc.MAXE = x.MAXE
	WHERE YEAR(NGAYLAP) =  @NAM and MONTH(NGAYLAP) = @THANG
	GROUP BY hx.MAHIEUXE, hx.TENHIEUXE
	ORDER BY SUM(psc.TONGTIEN) DESC
END
GO
EXEC GETCHITIETBAOCAO @THANG = 12, @NAM = 2022

INSERT INTO ACCOUNT(USERNAME, PASSWORD, TYPE) VALUES ('admin1', '-195-19811363614381088eq|-114086-7009477', 0)
GO
SELECT * FROM CT_BCDS

SELECT * FROM CHUXE
SELECT * FROM THAMSO