//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_PSC
    {
        public Nullable<int> MAPHIEU { get; set; }
        public Nullable<int> MANDTC { get; set; }
        public Nullable<decimal> TIENCONG { get; set; }
        public Nullable<int> MAPHUTUNG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public int MACTPSC { get; set; }
    
        public virtual PHUTUNG PHUTUNG { get; set; }
        public virtual PHIEUSUACHUA PHIEUSUACHUA { get; set; }
        public virtual TIENCONG TIENCONG1 { get; set; }
    }
}
