//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCDS
    {
        public int MACTBCDS { get; set; }
        public Nullable<System.DateTime> THANGNAM { get; set; }
        public Nullable<int> MAHIEUXE { get; set; }
        public Nullable<int> SOLUOTSUA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<double> TYLE { get; set; }
    
        public virtual HIEUXE HIEUXE { get; set; }
    }
}
