//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        public int SOPHIEUNHAP { get; set; }
        public int MAPHUTUNG { get; set; }
        public int SOLUONGNHAP { get; set; }
        public decimal DONGIA { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual PHUTUNG PHUTUNG { get; set; }
    }
}
