//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        public int MAPHIEUTHU { get; set; }
        public Nullable<System.DateTime> NGAYTHU { get; set; }
        public Nullable<int> MAXE { get; set; }
        public Nullable<decimal> SOTIENTHU { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
