//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUTUNG()
        {
            this.BAOCAOTONs = new HashSet<BAOCAOTON>();
            this.CHITIET_PSC = new HashSet<CHITIET_PSC>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
        }
    
        public int MAPHUTUNG { get; set; }
        public string TENPHUTUNG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAOTON> BAOCAOTONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PSC> CHITIET_PSC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
    }
}
