//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int MATHAMSO { get; set; }
        public string TENTHAMSO { get; set; }
        public Nullable<int> GIATRI { get; set; }
    }
}
